### ISSUE TITLE
Correctly loading XLS* Files

### ISSUE THREAD

**Issue by MarcusCalidus** [sergio-hcsoft/Delphi-SpreadSheets#2]
Hi, 

thank you very much for this tool. It helps us a lot while importing Excel files. I have found one issue if one wants to import XLSX or oder XML based Excel files. Since the extension is not equal to "xls" the object tries to load OpenOffice, which, in some cases is not installed on the machine.

You would have to change line 676 to:

```
IF (copy(UpperCase(ExtractFileExt(m_strFileName)),1,4) = '.XLS') THEN
```

cheers
Marco

**Comment by adnsistemas** [comment]
This is fixed in the pending pull request (and my clone of the repository), by using a function to determine if a file is an excel file.

**Comment by sergio-hcsoft** [comment]
Hi Marcus, this was fixed time ago as adnsistemas commented, in the current version it uses this function:

https://github.com/sergio-hcsoft/Delphi-SpreadSheets/blob/1af8e365a459384eade5fe66e0c63e65f3024192/UHojaCalc.pas#L1238-L1242
