### ISSUE TITLE
CloseProg is not closing the process of openoffice

### ISSUE THREAD

**Issue by Murilobeluco** [sergio-hcsoft/Delphi-SpreadSheets#4]
i'm using HojaCalc to create a xls file and after I save the file and free the THojaCalc object the openoffice process is still running and if I try to execute the output file It won't open because there is already a process running.

there is a way to close the process?

**Comment by sergio-hcsoft** [comment]
OpenOffice is not well suported, there is no info on how to work with it any longer. Once LibreOffice replaced it, we only tested on LibreOffice. I would suggest using LibreOffice instead or try to close the doc before closing the app (it is not bad that OpenOffice keeps opened as far as the file is freed correctly), but not really a guaranty of fixing it on OpenOffice.
